### ISSUE TITLE
geometry optimization doesn't work

### ISSUE THREAD

**Issue by wen-xl** [isayev/ASE_ANI#23]
Dear developers,

I'm running "ensemble_molecular_dynamics.ipynb" in example folder with a different geometry. I got the following error during the geometry optimization. It seems like some location is hard-coded to the developer's environment. How you have any suggestions to fix it?

ERROR: CUDA throw detected! Attempting to shut down nicely!
CUDA Error -- "an illegal memory access was encountered"
77 in location -- /nh/nest/u/jsmith/scratch/Gits/NeuroChem/src-aevlib/cuda_aev/cuaev_compute.cu:2511
 in function -- v_compute_aevec_components()

Traceback (most recent call last):
  File "ensemble_molecular_dynamics.py", line 73, in <module>
    dyn.run(fmax=0.001)
  File "/home/.local/lib/python3.6/site-packages/ase/optimize/optimize.py", line 202, in run
    for converged in self.irun(fmax, steps):
  File "/home/.local/lib/python3.6/site-packages/ase/optimize/optimize.py", line 175, in irun
    self.set_force_consistent()
  File "/home/.local/lib/python3.6/site-packages/ase/optimize/optimize.py", line 245, in set_force_consistent
    self.atoms.get_potential_energy(force_consistent=True)
  File "/home/.local/lib/python3.6/site-packages/ase/atoms.py", line 662, in get_potential_energy
    self, force_consistent=force_consistent)
  File "/home/.local/lib/python3.6/site-packages/ase/calculators/calculator.py", line 505, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/.local/lib/python3.6/site-packages/ase/calculators/calculator.py", line 552, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/software/ASE_ANI/lib/ase_interface.py", line 706, in calculate
    energy, force, stddev, Fstddev = self.nc.compute_mean_props()
  File "/home/software/ASE_ANI/lib/ase_interface.py", line 481, in compute_mean_props
    self.E[i] = nc.energy().copy()
RuntimeError: unidentifiable C++ exception

**Comment by wen-xl** [comment]
I originally used gromacs format geometry .gro. I converted it to .pdb, and then it worked.
