### ISSUE TITLE
problem installing ASED3

### ISSUE THREAD

**Issue by icamps** [isayev/ASE_ANI#24]
Hello,

I am trying to setting up ASE-ANI in my box with Linux Mint 19.1

When I run the test, I got:
`python3 ~/bin/ASE_ANI/examples/ani_quicktest.py 
van Der Waals correction will be unavailable. Please install ased3
Traceback (most recent call last):
  File "/home/icamps/bin/ASE_ANI/examples/ani_quicktest.py", line 16, in <module>
    mol = read('data/water.xyz')
  File "/usr/lib/python3/dist-packages/ase/io/formats.py", line 428, in read
    parallel=parallel, **kwargs))
  File "/usr/lib/python3/dist-packages/ase/io/formats.py", line 475, in _iread
    fd = open_with_compression(filename)
  File "/usr/lib/python3/dist-packages/ase/io/formats.py", line 286, in open_with_compression
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/water.xyz'
`

But trying to install ASED3, I got then (with python setup.py install):
`gfortran: error: build/temp.linux-x86_64-2.7/ased3/_d3params.o: No such file or directory gfortran: error: build/temp.linux-x86_64-2.7/ased3/_d3.o: No such file or directory gfortran: error: build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/_d3-f2pywrappers2.o: No such file or directory`

If I execute python3 setup.py install

I got:
`build/src.linux-x86_64-3.6/ased3/_d3module.c:17:10: fatal error: Python.h: No such file or directory #include "Python.h" ^~~~~~~~~~ compilation terminated. build/src.linux-x86_64-3.6/ased3/_d3module.c:17:10: fatal error: Python.h: No such file or directory #include "Python.h" ^~~~~~~~~~ compilation terminated. error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/ased3 -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.6m -c build/src.linux-x86_64-3.6/ased3/_d3module.c -o build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/ased3/_d3module.o -MMD -MF build/temp.linux-x86_64-3.6/build/src.linux-x86_64-3.6/ased3/_d3module.o.d" failed with exit status 1`

I appreciate any help.

Regards,

Camps

**Comment by isayev** [comment]
@icamps there are two separate errors. First "file not found" because in example  `ani_quicktest.py` we use a relative path.  Go to "~/bin/ASE_ANI/" and execute `python3 examples/ani_quicktest.py` one more time.

Second, D3 correction is totally optional, but if you'd like to have it, please try:
```
git clone https://github.com/isayev/ased3
cd ased3
python setup.py install
```

**Comment by icamps** [comment]
@isayev Thanks for the quick response!

I continue getting errors.

As I am beginning to play with ASE_ANI, I am not really sure if I will make use of D3 correction (probably yes), but at this time, I am just running the tests to see if the installation is ok, and I do not know how to disable the use of D3 in the examples.

I am confused. When I execute `python3 examples/ani_quicktest.py`, Iḿ using python3, but when installing ASED3 executing `python setup.py install` I am using python2.7, right?

Installing ASED3 with python, I got a different error now:
`fortran:f90: build/src.linux-x86_64-2.7/ased3/_d3-f2pywrappers2.f90
/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/_d3module.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/fortranobject.o build/temp.linux-x86_64-2.7/ased3/_d3params.o build/temp.linux-x86_64-2.7/ased3/_d3.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/_d3-f2pywrappers2.o -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -liomp5 -lgfortran -o build/lib.linux-x86_64-2.7/ased3/_d3.so
/usr/bin/ld: cannot find -liomp5
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/_d3module.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/fortranobject.o build/temp.linux-x86_64-2.7/ased3/_d3params.o build/temp.linux-x86_64-2.7/ased3/_d3.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/ased3/_d3-f2pywrappers2.o -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -liomp5 -lgfortran -o build/lib.linux-x86_64-2.7/ased3/_d3.so" failed with exit status 1`

If I try to install with `python3,` the error is the same as before: the file `Python.h` is missing. 

A rapid googling about  `/usr/bin/ld: cannot find -liomp5` give that it could be related with `python2-numpy-mkl`

I suppose that in order to use ASE_ANI (that is developed for Python3, I have to configure ASED3 with Python3 too, right?

**Comment by isayev** [comment]
1. No everything in python3.6!
2. Yes, you are missing liomp5, check if you have Intel MKL, or any other custom BLAS library installed. Often the problem is that your `$LD_LIBRARY_PATH` variable is not defined.

**Comment by UnixJunkie** [comment]
For the missing Python.h file; you might be missing some system package:
```bash
$ locate Python.h
[...]
/usr/include/python3.10/Python.h
[...]
$ dpkg -S /usr/include/python3.10/Python.h
libpython3.10-dev:amd64: /usr/include/python3.10/Python.h
```
I assume you are under a Debian-like Linux; if not then adapt commands to your Linux distro.
