### ISSUE TITLE
ImportError: ~/src/ASE_ANI/lib/libboost_python.so.1.63.0: undefined symbol: _Py_fopen

### ISSUE THREAD

**Issue by UnixJunkie** [isayev/ASE_ANI#45]
```bash
# ./test.sh 
Traceback (most recent call last):
  File "~/src/ASE_ANI/examples/ani_quicktest.py", line 6, in <module>
    from ase_interface import ANIENS
  File "~/src/ASE_ANI/lib/ase_interface.py", line 20, in <module>
    import pyNeuroChem as pync
ImportError: ~/src/ASE_ANI/lib/libboost_python.so.1.63.0: undefined symbol: _Py_fopen
```

**Comment by UnixJunkie** [comment]
Can reproduce by:
```bash
#!/bin/bash

export PATH=/usr/local/cuda-9.2/bin:${PATH}

export LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:${HOME}/src/ASE_ANI/lib:${LD_LIBRARY_PATH}

export PYTHONPATH=${HOME}/src/ASE_ANI/lib:${PYTHONPATH}

source bashrc_example.sh

python3 examples/ani_quicktest.py 
```

**Comment by UnixJunkie** [comment]
The cluster node I am using uses Ubuntu 22.04.3 LTS; if that helps.

**Comment by UnixJunkie** [comment]
I am stuck with this one; any help very welcome.

**Comment by proteneer** [comment]
well, time to unwatch this repo
